#!/usr/bin/env python3
"""Inject compact repository context at agent session start (Claude Code or Codex)."""
import json
import os
import subprocess
import sys
from pathlib import Path


POLICY = """Token-efficient repository workflow. Helpers live in `${CLAUDE_PLUGIN_ROOT:-$PLUGIN_ROOT}/scripts` (run with python3). Route by input:
| Input | Helper |
| repo orientation | agent_context.py |
| file/dir structure | outline.py |
| targeted file slice | safe_read.py |
| unknown-size command | run_capped.py -- CMD |
| test output | run_capped.py -- CMD |
| git changes | diff_summary.py |
| error-heavy logs | scan_errors.py / compact_logs.py |
| JSON shape | summarize_json.py |
| CSV/TSV/JSONL | summarize_data.py |
Search exact symbols first (`rg -n "sym" . | head -c 12000`), read slices instead of whole files, and use the Repository Context below before broad reads.
Redact secrets, keep scratch under `~/.codex/tmp`, keep Git read-only unless authorized, make the smallest scoped change, and report paths, line references, and anything not validated."""


def git_root(cwd):
    try:
        result = subprocess.run(
            ["git", "-C", cwd, "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=3,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    return result.stdout.strip() if result.returncode == 0 else None


def repository_context(cwd):
    root = git_root(cwd)
    plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT") or os.environ.get("PLUGIN_ROOT")
    if not root or not plugin_root:
        return ""
    helper = Path(plugin_root) / "scripts" / "agent_context.py"
    if not helper.is_file():
        return ""
    try:
        result = subprocess.run(
            [sys.executable, str(helper), root, "--max-output-chars", "4500"],
            capture_output=True,
            text=True,
            timeout=12,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def main():
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, OSError):
        payload = {}
    context = repository_context(payload.get("cwd") or str(Path.cwd()))
    additional = POLICY
    if context:
        additional += "\n\nRepository Context (generated by agent_context.py):\n" + context
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "SessionStart",
                    "additionalContext": additional,
                }
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
