#!/usr/bin/env python3
"""Inject compact repository context at agent session start (Claude Code or Codex)."""
import json
import os
import subprocess
import sys
from pathlib import Path


POLICY = """Token-efficient repo workflow. Search exact symbols first; outline likely files, then use safe_read.py for slices. Route tests and unknown output through run_capped.py; use diff_summary.py for Git, scan_errors.py/compact_logs.py for logs, summarize_json.py for JSON, and summarize_data.py for CSV/TSV/JSONL. Redact secrets, keep scratch under ~/.codex/tmp, keep Git read-only unless authorized, make the smallest scoped change, and report minimal validation."""

COMPACT_POLICY = (
    "Trust the compacted summary. Run agent_context.py only if repository state is missing or stale; "
    "then search exact symbols and read only the needed slices."
)


def git_root(cwd):
    try:
        result = subprocess.run(
            ["git", "-C", cwd, "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=3,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    return result.stdout.strip() if result.returncode == 0 else None


def repository_context(cwd):
    root = git_root(cwd)
    plugin_root = os.environ.get("CLAUDE_PLUGIN_ROOT") or os.environ.get("PLUGIN_ROOT")
    if not root or not plugin_root:
        return ""
    helper = Path(plugin_root) / "scripts" / "agent_context.py"
    if not helper.is_file():
        return ""
    try:
        result = subprocess.run(
            [sys.executable, str(helper), root, "--max-output-chars", "3000"],
            capture_output=True,
            text=True,
            timeout=12,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def main():
    # Read stdin fully as bytes first so the harness's payload write never
    # hits a closed pipe (EPIPE), even on invalid JSON or bad encoding.
    try:
        payload = json.loads(sys.stdin.buffer.read().decode("utf-8", errors="replace"))
    except (json.JSONDecodeError, OSError, ValueError):
        payload = {}
    if not isinstance(payload, dict):
        payload = {}
    if payload.get("source", "startup") == "compact":
        additional = COMPACT_POLICY
        context = ""
    else:
        context = repository_context(payload.get("cwd") or str(Path.cwd()))
        additional = POLICY
    if context:
        additional += "\n\nRepository Context (generated by agent_context.py):\n" + context
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "SessionStart",
                    "additionalContext": additional,
                }
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
