#!/usr/bin/env python3
"""Inject compact repository context at Codex session start."""
import json
import os
import subprocess
import sys
from pathlib import Path


POLICY = """Token-efficient repository workflow:
- Use the supplied Repository Context and its Next Token-Safe Steps before broad reads.
- Prefer indexed code/search tools when available; otherwise use exact `rg`, then `outline.py` and `safe_read.py`.
- Route unknown-size output, tests, logs, diffs, JSON, and tabular data through the installed `~/.agents/scripts` helpers.
- Redact secrets, keep scratch output under `~/.codex/tmp`, preserve user changes, and keep Git read-only unless authorized.
- Make the smallest scoped change, run the smallest useful validation, and report paths, line references, status, and anything not validated."""


def git_root(cwd):
    try:
        result = subprocess.run(
            ["git", "-C", cwd, "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            timeout=3,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    return result.stdout.strip() if result.returncode == 0 else None


def repository_context(cwd):
    root = git_root(cwd)
    helper_root = Path(os.environ["PLUGIN_ROOT"]) if os.environ.get("PLUGIN_ROOT") else Path.home() / ".agents"
    helper = helper_root / "scripts" / "agent_context.py"
    if not root or not helper.is_file():
        return ""
    try:
        result = subprocess.run(
            [sys.executable, str(helper), root, "--max-output-chars", "6000"],
            capture_output=True,
            text=True,
            timeout=12,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def main():
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, OSError):
        payload = {}
    context = repository_context(payload.get("cwd") or str(Path.cwd()))
    additional = POLICY
    if context:
        additional += "\n\nRepository Context (generated by agent_context.py):\n" + context
    print(
        json.dumps(
            {
                "hookSpecificOutput": {
                    "hookEventName": "SessionStart",
                    "additionalContext": additional,
                }
            }
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
